apiVersion: v1
kind: Service
metadata:
  name: emoticare-service
  namespace: emoticare
spec:
  selector:
    app: emoticare
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
